name: ci

on:
  workflow_dispatch:
    inputs:
      BuildConfiguration:
        type: string
        description: Build Configuration
        required: true
        default: Release
      PublishPreview:
        type: boolean
        description: Publish preview branch?
        required: true
        default: false
  push:
    branches-ignore:
      - "preview/**"
    paths-ignore:
      - ".azure-pipelines/**"
      - LICENSE
      - README.md
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  compliance:
    uses: f2calv/ghaction_workflows/.github/workflows/dotnet-nuget-publish-v1.yml@main
